import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";
import { AboutHero, AboutLinkGrid, AboutShell, CommitmentList, EditorialSection, LetterStory, PhilosophyQuote } from "@/components/about";

export const metadata: Metadata = pageMetadata("About", "Learn about the people, gratitude, and purpose behind AAN Legacy Foundation.", "/about");

export default function AboutPage() {
  return <AboutShell><AboutHero eyebrow="About AAN" title="A foundation shaped by gratitude and guided by purpose." description="AAN Legacy Foundation exists to create opportunities, support vulnerable people, empower young people, and build a lasting legacy." /><EditorialSection eyebrow="An introduction" title="Meaningful change can begin with one person."><div className="space-y-6 text-base leading-8"><p>One person can change a family. One family can change a generation. One generation can change the world.</p><p>AAN carries that belief into practical commitments to education, scholarships, youth empowerment, mentorship, humanitarian support, and community development.</p></div></EditorialSection><EditorialSection eyebrow="Why AAN?" title="A name held by many."><div className="space-y-8"><PhilosophyQuote>AAN is not only a name. It represents people, gratitude, purpose, and a commitment to impact lives.</PhilosophyQuote><p className="text-base leading-8">The foundation was inspired by the positive role the Amoako, Anson, and Nyarko families played in Moses&apos; academic and personal journey. This gratitude now points outward, toward a broader purpose of creating opportunity for others.</p></div></EditorialSection><section className="section-shell py-20 lg:py-28"><div className="mb-12"><p className="eyebrow">The meaning behind AAN</p><h2 className="display-text mt-4 max-w-2xl text-4xl leading-tight text-[var(--forest-950)] sm:text-5xl">Three names. One shared legacy.</h2></div><LetterStory /></section><section className="bg-[var(--paper)] py-20 lg:py-28"><div className="section-shell"><div className="mb-12"><p className="eyebrow">Our commitments</p><h2 className="display-text mt-4 max-w-2xl text-4xl leading-tight text-[var(--forest-950)] sm:text-5xl">People are at the heart of the work.</h2></div><CommitmentList /></div></section><section className="section-shell py-20 lg:py-28"><div className="mb-12"><p className="eyebrow">Explore AAN</p><h2 className="display-text mt-4 max-w-2xl text-4xl leading-tight text-[var(--forest-950)] sm:text-5xl">Follow the story further.</h2></div><AboutLinkGrid /></section></AboutShell>;
}
