"use client";

import { useState } from "react";

type EventRecord = { id: string; title: string; slug: string; startsAt: string; status: string; capacity: number | null; _count: { registrations: number } };
const empty = { title: "", slug: "", summary: "", description: "", startsAt: "", location: "", capacity: "", registrationDeadline: "", status: "DRAFT" };

export default function AdminEventsPage() {
  const [token, setToken] = useState(""); const [events, setEvents] = useState<EventRecord[]>([]); const [form, setForm] = useState(empty); const [message, setMessage] = useState("Enter the CMS token to manage events.");
  async function load() { const response = await fetch("/api/admin/events", { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "Unable to load events."); return; } setEvents(data); setMessage(""); }
  async function create(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/events", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...form, capacity: form.capacity ? Number(form.capacity) : null, endsAt: null, featuredImage: null, registrationDeadline: form.registrationDeadline || null }) }); const data = await response.json(); setMessage(response.ok ? "Event created." : data.error || "Unable to create event."); if (response.ok) { setForm(empty); load(); } }
  async function cancel(id: string) { if (!window.confirm("Cancel this event?")) return; await fetch(`/api/admin/events/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); load(); }
  async function exportRegistrations(id: string) { const response = await fetch(`/api/admin/events/${id}/registrations?format=csv`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) { setMessage("Unable to export registrations."); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "event-registrations.csv"; link.click(); URL.revokeObjectURL(url); }
  return <main className="section-shell min-h-screen py-16"><p className="eyebrow">Admin · Events</p><h1 className="display-text mt-4 text-5xl text-[var(--forest-950)]">Event management</h1><div className="mt-8 flex max-w-2xl gap-3"><input className="form-control" type="password" placeholder="CMS token" value={token} onChange={(event) => setToken(event.target.value)} /><button onClick={load} className="bg-[var(--forest-950)] px-5 text-sm font-bold text-white">Load</button></div><form onSubmit={create} className="surface-card mt-8 max-w-3xl space-y-4 p-6"><p className="eyebrow">Create event</p><div className="grid gap-4 sm:grid-cols-2">{(["title", "slug", "location", "startsAt", "capacity", "registrationDeadline"] as const).map((field) => <label key={field} className="text-sm font-semibold">{field.replace(/[A-Z]/g, (letter) => ` ${letter.toLowerCase()}`)}<input className="form-control mt-2" type={field === "capacity" ? "number" : field.includes("At") || field.includes("Deadline") ? "datetime-local" : "text"} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} required={field === "title" || field === "slug" || field === "startsAt"} /></label>)}</div><label className="block text-sm font-semibold">Summary<textarea className="form-control mt-2" value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} required /></label><label className="block text-sm font-semibold">Description<textarea className="form-control mt-2" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} required /></label><button className="bg-[var(--forest-950)] px-5 py-3 text-sm font-bold text-white">Create event</button><p className="text-sm text-[var(--muted)]">{message}</p></form><section className="mt-12"><h2 className="display-text text-3xl text-[var(--forest-950)]">Events</h2><div className="mt-5 divide-y divide-[var(--line)] border-y border-[var(--line)]">{events.map((event) => <div key={event.id} className="flex flex-col gap-3 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{event.title}</p><p className="text-sm text-[var(--muted)]">{new Date(event.startsAt).toLocaleString()} · {event._count.registrations}{event.capacity ? ` / ${event.capacity}` : ""} registered · {event.status}</p></div><div className="flex gap-3"><button className="text-sm font-bold text-[var(--forest-800)]" onClick={() => exportRegistrations(event.id)}>Export CSV</button><button onClick={() => cancel(event.id)} className="text-sm font-bold text-[var(--danger)]">Cancel</button></div></div>)}</div></section></main>;
}
